name: FAS WEB CI

on:
  pull_request:
    branches:
      - main
      - feature*
    paths:
      - "**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  fas-ui-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/frontend-ci.yaml@main
    with:
      node_version: "20.5.1"
      app_name: "fas-ui"
      working_directory: "."
      codecov_flag: "payweb"
